apiVersion: v1
kind: Service
metadata:
  name: dx03-backend
  namespace: dx03-ENVIRONMENT_PLACEHOLDER
  labels:
    app: dx03-backend
spec:
  type: ClusterIP
  selector:
    app: dx03-backend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
