apiVersion: v1
kind: Service
metadata:
  name: dx03-frontend
  namespace: dx03-ENVIRONMENT_PLACEHOLDER
  labels:
    app: dx03-frontend
spec:
  type: ClusterIP
  selector:
    app: dx03-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
