apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: dx03-frontend-config
  namespace: NAMESPACE_PLACEHOLDER
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: "MOVED_PERMANENTLY_DEFAULT"
